server:
  port: 8090

spring:
  application:
    name: campaign-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=WayzyDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  cloud:
    config:
      uri: http://localhost:8080
      fail-fast: true
      retry:
        max-attempts: 6
        multiplier: 1.2
        initial-interval: 1000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.phenikaa.campaignService: DEBUG

