service:
  port: 8083

spring:
  application:
    name: user-service

    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=user_db;encrypt=false
      username: sa
      password: 142857
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE