server:
  port: 8084

spring:
  application:
    name: tour-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=tour_db;encrypt=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create   # (create, create-drop, validate, update)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE